### PR TITLE
Allow to open context menu at exact position

### LINKED ISSUE #31: Be Able to Disable Automatic Positioning of Context Menu
The context menu is [positioned automatically depending on how much space there is on the screen](https://github.com/bpmn-io/table-js/blob/master/src/features/context-menu/components/ContextMenuComponent.js#L241). There should be an option for disabling that automatic positioning.

Related to https://github.com/bpmn-io/dmn-js/pull/526

### PR DESCRIPTION
**Pull request by barmac**
To use the feature, pass `exact=true` in context menu position.

Closes #31

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Does this need any extra steps in dmn-js-decision-table? E.g. setting the property.

**Comment by barmac** [comment]
Yes, you have to add `exact=true` in the position object when you open context menu. I have already prepared a solution for dmn-js which works when you link this PR. It's on [this branch](https://github.com/bpmn-io/dmn-js/tree/open-input-output-editing-at-exact-position)

**Comment by philippfromme** [comment]
I would have suggested a different way of disabling automatic alignment. `exact` doesn't really tell me what's going to happen. The context menu is always going to open at the exact position it's supposed to. The question is whether it will open to the top or bottom and to the right or left. So I would have suggested something like `align=bottom-right` which would ensure that the context menu opens to the bottom right. Unfortunately, the PR has already been merged.

**Comment by barmac** [comment]
There are no irreversible commits ;). So if I get it correctly, you suggest to change the API to the following:

```javascript
contextMenu.open({ x: 0, y: 0, align: 'bottom-right' });
```

Right?

**Comment by philippfromme** [comment]
Yes, that way you could specify exactly how you want the context menu to open.

**Pull request merged**
