### PR TITLE
feat(render): fire event on container scroll

### PR DESCRIPTION
**Pull request by philippfromme**
Related to https://github.com/bpmn-io/dmn-js/pull/654.

### CODE REVIEW

**Comment by MaxTru** [comment]
Shall this be reviewed? (it is in draft stage?)

**Comment by philippfromme** [comment]
> Shall this be reviewed? (it is in draft stage?)

Sorry, forgot to change from draft.

**Comment by philippfromme** [comment]
Once this is merged I will release `table-js` in order to integrate it into https://github.com/bpmn-io/dmn-js/pull/654.

**Review by nikku — APPROVED** [review]
:clap:

**Pull request merged**
